-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\USER\Desktop\Farneback_blockRAM\blockram_v2\codegen\PolyExp_pipeline1\hdlsrc\PolyExp_pipeline1_fixpt.vhd
-- Created: 2020-06-05 16:17:03
-- 
-- Generated by MATLAB 9.7, MATLAB Coder 4.3 and HDL Coder 3.15
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Design base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PolyExp_pipeline1_fixpt
-- Source Path: PolyExp_pipeline1_fixpt
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY PolyExp_pipeline1_fixpt IS
  PORT( indatasrc                         :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        outdata                           :   OUT   std_logic_vector(13 DOWNTO 0)  -- ufix14_En7
        );
END PolyExp_pipeline1_fixpt;


ARCHITECTURE rtl OF PolyExp_pipeline1_fixpt IS

  -- Signals
  SIGNAL indatasrc_unsigned               : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL outdata_tmp                      : unsigned(13 DOWNTO 0);  -- ufix14_En7
  SIGNAL PolyExp_pipeline1_fixpt_mul_temp : unsigned(21 DOWNTO 0);  -- ufix22_En15

BEGIN
  indatasrc_unsigned <= unsigned(indatasrc);

  --HDL code generation from MATLAB function: PolyExp_pipeline1_fixpt
  --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  --                                                                          %
  --           Generated by MATLAB 9.7 and Fixed-Point Designer 6.4           %
  --                                                                          %
  --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  PolyExp_pipeline1_fixpt_mul_temp <= indatasrc_unsigned * to_unsigned(16#2A8D#, 14);
  outdata_tmp <= PolyExp_pipeline1_fixpt_mul_temp(21 DOWNTO 8);

  outdata <= std_logic_vector(outdata_tmp);

END rtl;

