%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.7 and Fixed-Point Designer 6.4           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [drow_1,drow_2,drow_3,drow_4,drow_5] = PolyExp_pipeline4_wrapper_fixpt(data_in_0,data_in_1,data_in_2)
    fm = get_fimath();
    data_in_0_in = fi( data_in_0, 0, 14, 6, fm );
    data_in_1_in = fi( data_in_1, 1, 14, 6, fm );
    data_in_2_in = fi( data_in_2, 0, 14, 5, fm );
    [drow_1_out,drow_2_out,drow_3_out,drow_4_out,drow_5_out] = PolyExp_pipeline4_fixpt( data_in_0_in, data_in_1_in, data_in_2_in );
    drow_1 = double( drow_1_out );
    drow_2 = double( drow_2_out );
    drow_3 = double( drow_3_out );
    drow_4 = double( drow_4_out );
    drow_5 = double( drow_5_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
