%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.7 and Fixed-Point Designer 6.4           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [drow_1,drow_2,drow_3,drow_4,drow_5] = PolyExp_pipeline4_fixpt(data_in_0,data_in_1,data_in_2)
%--------------------------------------------								
fm = get_fimath();

n = fi(8, 0, 4, 0, fm);			
width  = fi(200, 0, 8, 0, fm);
%--------------------------------------------
g    = fi(zeros(1,fi_toint(n*fi(6, 0, 3, 0, fm) + fi(3, 0, 2, 0, fm) + n)), 0, 14, 15, fm);
xg   = fi(zeros(1,fi_toint(n*fi(6, 0, 3, 0, fm) + fi(3, 0, 2, 0, fm) + n + n*fi(2, 0, 2, 0, fm) + fi(1, 0, 1, 0, fm))), 1, 14, 15, fm);
xxg  = fi(zeros(1,fi_toint(n*fi(6, 0, 3, 0, fm) + fi(3, 0, 2, 0, fm) + n + n*fi(2, 0, 2, 0, fm) + fi(1, 0, 1, 0, fm) + n*fi(2, 0, 2, 0, fm) + fi(1, 0, 1, 0, fm))), 0, 14, 15, fm);
%--------------------------------------------
persistent rRam1 rRam2 rRam3 ctr;
if isempty(ctr)
	ctr = fi(uint8(1), 0, 8, 0, fm);
end
if isempty(rRam1)
	rRam1 = fi(zeros(1,fi_toint(width)), 0, 14, 6, fm);
end		
if isempty(rRam2)
	rRam2 = fi(zeros(1,fi_toint(width)), 1, 14, 6, fm);
end	
if isempty(rRam3)
	rRam3 = fi(zeros(1,fi_toint(width)), 0, 14, 5, fm);
end		
%----------------------
g(1, 1) = 7.425750567660737e-11;  xg(1, 1) = -5.940600454128590e-10; xxg(1, 1) = 4.752480363302872e-09;
g(1, 2) = 1.357346656654903e-08;  xg(1, 2) = -9.501426596584319e-08; xxg(1, 2) = 6.650998617609023e-07;
g(1, 3) = 1.238932971502896e-06;  xg(1, 3) = -7.433597829017376e-06; xxg(1, 3) = 4.460158697410425e-05;
g(1, 4) = 5.646917756715771e-05;  xg(1, 4) = -2.823458878357885e-04; xxg(1, 4) = 0.001411729439179;
g(1, 5) = 0.001285225836022;      xg(1, 5) = -0.005140903344087;     xxg(1, 5) = 0.020563613376348;
g(1, 6) = 0.014606906292119;      xg(1, 6) = -0.043820718876357;     xxg(1, 6) = 0.131462156629071;
g(1, 7) = 0.082897614969052;      xg(1, 7) = -0.165795229938103;     xxg(1, 7) = 0.331590459876207;
g(1, 8) = 0.234926576512800;      xg(1, 8) = -0.234926576512800;     xxg(1, 8) = 0.234926576512800;
g(1, 9) = 0.332451909263490;      xg(1, 9) = 0.0;                    xxg(1, 9) = 0.0;
g(1,10) = 0.234926576512800;      xg(1,10) = 0.234926576512800;      xxg(1,10) = 0.234926576512800;
g(1,11) = 0.082897614969052;      xg(1,11) = 0.165795229938103;      xxg(1,11) = 0.331590459876207;
g(1,12) = 0.014606906292119;      xg(1,12) = 0.043820718876357;      xxg(1,12) = 0.131462156629071;
g(1,13) = 0.001285225836022;      xg(1,13) = 0.005140903344087;      xxg(1,13) = 0.020563613376348;
g(1,14) = 5.646917756715771e-05;  xg(1,14) = 2.823458878357885e-04;  xxg(1,14) = 0.001411729439179;
g(1,15) = 1.238932971502896e-06;  xg(1,15) = 7.433597829017376e-06;  xxg(1,15) = 4.460158697410425e-05;
g(1,16) = 1.357346656654903e-08;  xg(1,16) = 9.501426596584319e-08;  xxg(1,16) = 6.650998617609023e-07;
g(1,17) = 7.425750567660737e-11;  xg(1,17) = 5.940600454128590e-10;  xxg(1,17) = 4.752480363302872e-09;
ig11 = fi(0.6944, 0, 14, 14, fm); ig03 = fi(-0.3472, 1, 14, 14, fm); ig33 = fi(0.2411, 0, 14, 16, fm); ig55 = fi(0.4823, 0, 14, 15, fm);
%----------------------
BRAM_in_1 = fi(data_in_0, 0, 14, 6, fm);
BRAM_in_2 = fi(data_in_1, 1, 14, 6, fm);
BRAM_in_3 = fi(data_in_2, 0, 14, 5, fm);
%---------------------- write BRAM
writeData_1 = fi(BRAM_in_1, 0, 14, 6, fm);
writeData_2 = fi(BRAM_in_2, 1, 14, 6, fm);
writeData_3 = fi(BRAM_in_3, 0, 14, 5, fm);
rRam1(ctr) = writeData_1;
rRam2(ctr) = writeData_2;
rRam3(ctr) = writeData_3;
%---------------------- read BRAM
readData_1 = fi(rRam1(ctr), 0, 14, 6, fm);
readData_2 = fi(rRam2(ctr), 1, 14, 6, fm);
readData_3 = fi(rRam3(ctr), 0, 14, 5, fm);
BRAM_out_1 = fi(readData_1, 0, 14, 6, fm);
BRAM_out_2 = fi(readData_2, 1, 14, 6, fm);
BRAM_out_3 = fi(readData_3, 0, 14, 5, fm);
%----------------------
inb1 = fi(BRAM_out_1*g(1, 9), 0, 14, 6, fm);
inb2 = fi(0.0, 1, 14, 6, fm);
inb3 = fi(BRAM_out_2*g(1, 9), 1, 14, 6, fm);
inb4 = fi(0.0, 0, 14, 5, fm);
inb5 = fi(BRAM_out_3*g(1, 9), 0, 14, 5, fm);
inb6 = fi(0.0, 1, 14, 6, fm);
%----------------------
rRam1_P_1 = fi(rRam1(min(ctr+fi(1, 0, 1, 0, fm),fi(200, 0, 8, 0, fm))), 0, 14, 6, fm);
rRam1_P_2 = fi(rRam1(min(ctr+fi(2, 0, 2, 0, fm),fi(200, 0, 8, 0, fm))), 0, 14, 6, fm);
rRam1_P_3 = fi(rRam1(min(ctr+fi(3, 0, 2, 0, fm),fi(200, 0, 8, 0, fm))), 0, 14, 6, fm);
rRam1_P_4 = fi(rRam1(min(ctr+fi(4, 0, 3, 0, fm),fi(200, 0, 8, 0, fm))), 0, 14, 6, fm);
rRam1_P_5 = fi(rRam1(min(ctr+fi(5, 0, 3, 0, fm),fi(200, 0, 8, 0, fm))), 0, 14, 6, fm);
rRam1_P_6 = fi(rRam1(min(ctr+fi(6, 0, 3, 0, fm),fi(200, 0, 8, 0, fm))), 0, 14, 6, fm);
rRam1_P_7 = fi(rRam1(min(ctr+fi(7, 0, 3, 0, fm),fi(200, 0, 8, 0, fm))), 0, 14, 6, fm);
rRam1_P_8 = fi(rRam1(min(ctr+fi(8, 0, 4, 0, fm),fi(200, 0, 8, 0, fm))), 0, 14, 6, fm);
rRam1_N_1 = fi(rRam1(max(ctr-fi(1, 0, 1, 0, fm),fi(1, 0, 1, 0, fm))), 0, 14, 6, fm);
rRam1_N_2 = fi(rRam1(max(ctr-fi(2, 0, 2, 0, fm),fi(1, 0, 1, 0, fm))), 0, 14, 6, fm);
rRam1_N_3 = fi(rRam1(max(ctr-fi(3, 0, 2, 0, fm),fi(1, 0, 1, 0, fm))), 0, 14, 6, fm);
rRam1_N_4 = fi(rRam1(max(ctr-fi(4, 0, 3, 0, fm),fi(1, 0, 1, 0, fm))), 0, 14, 6, fm);
rRam1_N_5 = fi(rRam1(max(ctr-fi(5, 0, 3, 0, fm),fi(1, 0, 1, 0, fm))), 0, 14, 6, fm);
rRam1_N_6 = fi(rRam1(max(ctr-fi(6, 0, 3, 0, fm),fi(1, 0, 1, 0, fm))), 0, 14, 6, fm);
rRam1_N_7 = fi(rRam1(max(ctr-fi(7, 0, 3, 0, fm),fi(1, 0, 1, 0, fm))), 0, 14, 6, fm);
rRam1_N_8 = fi(rRam1(max(ctr-fi(8, 0, 4, 0, fm),fi(1, 0, 1, 0, fm))), 0, 14, 6, fm);
%----------------------
rRam2_P_1 = fi(rRam2(min(ctr+fi(1, 0, 1, 0, fm),fi(200, 0, 8, 0, fm))), 1, 14, 6, fm);
rRam2_P_2 = fi(rRam2(min(ctr+fi(2, 0, 2, 0, fm),fi(200, 0, 8, 0, fm))), 1, 14, 6, fm);
rRam2_P_3 = fi(rRam2(min(ctr+fi(3, 0, 2, 0, fm),fi(200, 0, 8, 0, fm))), 1, 14, 6, fm);
rRam2_P_4 = fi(rRam2(min(ctr+fi(4, 0, 3, 0, fm),fi(200, 0, 8, 0, fm))), 1, 14, 6, fm);
rRam2_P_5 = fi(rRam2(min(ctr+fi(5, 0, 3, 0, fm),fi(200, 0, 8, 0, fm))), 1, 14, 6, fm);
rRam2_P_6 = fi(rRam2(min(ctr+fi(6, 0, 3, 0, fm),fi(200, 0, 8, 0, fm))), 1, 14, 6, fm);
rRam2_P_7 = fi(rRam2(min(ctr+fi(7, 0, 3, 0, fm),fi(200, 0, 8, 0, fm))), 1, 14, 6, fm);
rRam2_P_8 = fi(rRam2(min(ctr+fi(8, 0, 4, 0, fm),fi(200, 0, 8, 0, fm))), 1, 14, 6, fm);
rRam2_N_1 = fi(rRam2(max(ctr-fi(1, 0, 1, 0, fm),fi(1, 0, 1, 0, fm))), 1, 14, 6, fm);
rRam2_N_2 = fi(rRam2(max(ctr-fi(2, 0, 2, 0, fm),fi(1, 0, 1, 0, fm))), 1, 14, 6, fm);
rRam2_N_3 = fi(rRam2(max(ctr-fi(3, 0, 2, 0, fm),fi(1, 0, 1, 0, fm))), 1, 14, 6, fm);
rRam2_N_4 = fi(rRam2(max(ctr-fi(4, 0, 3, 0, fm),fi(1, 0, 1, 0, fm))), 1, 14, 6, fm);
rRam2_N_5 = fi(rRam2(max(ctr-fi(5, 0, 3, 0, fm),fi(1, 0, 1, 0, fm))), 1, 14, 6, fm);
rRam2_N_6 = fi(rRam2(max(ctr-fi(6, 0, 3, 0, fm),fi(1, 0, 1, 0, fm))), 1, 14, 6, fm);
rRam2_N_7 = fi(rRam2(max(ctr-fi(7, 0, 3, 0, fm),fi(1, 0, 1, 0, fm))), 1, 14, 6, fm);
rRam2_N_8 = fi(rRam2(max(ctr-fi(8, 0, 4, 0, fm),fi(1, 0, 1, 0, fm))), 1, 14, 6, fm);
%----------------------
rRam3_P_1 = fi(rRam3(min(ctr+fi(1, 0, 1, 0, fm),fi(200, 0, 8, 0, fm))), 0, 14, 5, fm);
rRam3_P_2 = fi(rRam3(min(ctr+fi(2, 0, 2, 0, fm),fi(200, 0, 8, 0, fm))), 0, 14, 5, fm);
rRam3_P_3 = fi(rRam3(min(ctr+fi(3, 0, 2, 0, fm),fi(200, 0, 8, 0, fm))), 0, 14, 5, fm);
rRam3_P_4 = fi(rRam3(min(ctr+fi(4, 0, 3, 0, fm),fi(200, 0, 8, 0, fm))), 0, 14, 5, fm);
rRam3_P_5 = fi(rRam3(min(ctr+fi(5, 0, 3, 0, fm),fi(200, 0, 8, 0, fm))), 0, 14, 5, fm);
rRam3_P_6 = fi(rRam3(min(ctr+fi(6, 0, 3, 0, fm),fi(200, 0, 8, 0, fm))), 0, 14, 5, fm);
rRam3_P_7 = fi(rRam3(min(ctr+fi(7, 0, 3, 0, fm),fi(200, 0, 8, 0, fm))), 0, 14, 5, fm);
rRam3_P_8 = fi(rRam3(min(ctr+fi(8, 0, 4, 0, fm),fi(200, 0, 8, 0, fm))), 0, 14, 5, fm);
rRam3_N_1 = fi(rRam3(max(ctr-fi(1, 0, 1, 0, fm),fi(1, 0, 1, 0, fm))), 0, 14, 5, fm);
rRam3_N_2 = fi(rRam3(max(ctr-fi(2, 0, 2, 0, fm),fi(1, 0, 1, 0, fm))), 0, 14, 5, fm);
rRam3_N_3 = fi(rRam3(max(ctr-fi(3, 0, 2, 0, fm),fi(1, 0, 1, 0, fm))), 0, 14, 5, fm);
rRam3_N_4 = fi(rRam3(max(ctr-fi(4, 0, 3, 0, fm),fi(1, 0, 1, 0, fm))), 0, 14, 5, fm);
rRam3_N_5 = fi(rRam3(max(ctr-fi(5, 0, 3, 0, fm),fi(1, 0, 1, 0, fm))), 0, 14, 5, fm);
rRam3_N_6 = fi(rRam3(max(ctr-fi(6, 0, 3, 0, fm),fi(1, 0, 1, 0, fm))), 0, 14, 5, fm);
rRam3_N_7 = fi(rRam3(max(ctr-fi(7, 0, 3, 0, fm),fi(1, 0, 1, 0, fm))), 0, 14, 5, fm);
rRam3_N_8 = fi(rRam3(max(ctr-fi(8, 0, 4, 0, fm),fi(1, 0, 1, 0, fm))), 0, 14, 5, fm);
%----------------------
inb1_P = fi(0, 0, 14, 6, fm);
inb1_N = fi(0, 0, 14, 6, fm);
inb2_P = fi(0, 1, 14, 6, fm);
inb2_N = fi(0, 1, 14, 6, fm);
inb3_P = fi(0, 0, 14, 5, fm);
inb3_N = fi(0, 0, 14, 5, fm);
for k = fi(1, 0, 1, 0, fm): n
	if k == fi(1, 0, 1, 0, fm)
		inb1_P(:) = rRam1_P_1;
		inb1_N(:) = rRam1_N_1;
		inb2_P(:) = rRam2_P_1;
		inb2_N(:) = rRam2_N_1;
		inb3_P(:) = rRam3_P_1;
		inb3_N(:) = rRam3_N_1;
	elseif k == fi(2, 0, 2, 0, fm)
		inb1_P(:) = rRam1_P_2;
		inb1_N(:) = rRam1_N_2;
		inb2_P(:) = rRam2_P_2;
		inb2_N(:) = rRam2_N_2;
		inb3_P(:) = rRam3_P_2;
		inb3_N(:) = rRam3_N_2;
	elseif k == fi(3, 0, 2, 0, fm)
		inb1_P(:) = rRam1_P_3;
		inb1_N(:) = rRam1_N_3;
		inb2_P(:) = rRam2_P_3;
		inb2_N(:) = rRam2_N_3;
		inb3_P(:) = rRam3_P_3;
		inb3_N(:) = rRam3_N_3;
	elseif k == fi(4, 0, 3, 0, fm)
		inb1_P(:) = rRam1_P_4;
		inb1_N(:) = rRam1_N_4;
		inb2_P(:) = rRam2_P_4;
		inb2_N(:) = rRam2_N_4;
		inb3_P(:) = rRam3_P_4;
		inb3_N(:) = rRam3_N_4;
	elseif k == fi(5, 0, 3, 0, fm)
		inb1_P(:) = rRam1_P_5;
		inb1_N(:) = rRam1_N_5;
		inb2_P(:) = rRam2_P_5;
		inb2_N(:) = rRam2_N_5;
		inb3_P(:) = rRam3_P_5;
		inb3_N(:) = rRam3_N_5;
	elseif k == fi(6, 0, 3, 0, fm)
		inb1_P(:) = rRam1_P_6;
		inb1_N(:) = rRam1_N_6;
		inb2_P(:) = rRam2_P_6;
		inb2_N(:) = rRam2_N_6;
		inb3_P(:) = rRam3_P_6;
		inb3_N(:) = rRam3_N_6;
	elseif k == fi(7, 0, 3, 0, fm)
		inb1_P(:) = rRam1_P_7;
		inb1_N(:) = rRam1_N_7;
		inb2_P(:) = rRam2_P_7;
		inb2_N(:) = rRam2_N_7;
		inb3_P(:) = rRam3_P_7;
		inb3_N(:) = rRam3_N_7;
	elseif k == fi(8, 0, 4, 0, fm)
		inb1_P(:) = rRam1_P_8;
		inb1_N(:) = rRam1_N_8;
		inb2_P(:) = rRam2_P_8;
		inb2_N(:) = rRam2_N_8;
		inb3_P(:) = rRam3_P_8;
		inb3_N(:) = rRam3_N_8;
	end
	
	tg = fi(inb1_P + inb1_N, 0, 14, 5, fm);
	g0 = fi(g(1,k+fi(9, 0, 4, 0, fm)), 0, 14, 16, fm);
	outb1 = fi(inb1 + tg * g0, 0, 14, 6, fm);
	outb4 = fi(inb4 + tg * xxg(1,k+fi(9, 0, 4, 0, fm)), 0, 14, 5, fm);
	outb2 = fi(inb2 + (fi_signed(inb1_P) - inb1_N) * xg(1,k+fi(9, 0, 4, 0, fm)), 1, 14, 6, fm);
	outb3 = fi(inb3 + (inb2_P + inb2_N) * g0, 1, 14, 6, fm);
	outb6 = fi(inb6 + (inb2_P - inb2_N) * xg(1,k+fi(9, 0, 4, 0, fm)), 1, 14, 6, fm);
	outb5 = fi(inb5 + (inb3_P + inb3_N) * g0, 0, 14, 5, fm);
	
	inb1(:) = outb1;
	inb2(:) = outb2;
	inb3(:) = outb3;
	inb4(:) = outb4;
	inb5(:) = outb5;
	inb6(:) = outb6;
end

outb1 = fi(inb1, 0, 14, 6, fm);
outb2 = fi(inb2, 1, 14, 6, fm);
outb3 = fi(inb3, 1, 14, 6, fm);
outb4 = fi(inb4, 0, 14, 5, fm);
outb5 = fi(inb5, 0, 14, 5, fm);
outb6 = fi(inb6, 1, 14, 6, fm);
%----------------------
drow_1 = fi(outb2*ig11, 1, 14, 6, fm);
drow_2 = fi(outb3*ig11, 1, 14, 7, fm);
drow_3 = fi(outb1*ig03 + outb4*ig33, 1, 14, 8, fm);
drow_4 = fi(outb1*ig03 + outb5*ig33, 1, 14, 8, fm);
drow_5 = fi(outb6*ig55, 1, 14, 7, fm);
%---------------------- ctr counter
if ctr == uint8(200)
	ctr(:) = uint8(1);
else
	ctr(:) = ctr + fi(1, 0, 1, 0, fm);
end
%----------------------
end



function y = fi_signed(a)
    coder.inline( 'always' );
    if isfi( a ) && ~(issigned( a ))
        nt = numerictype( a );
        new_nt = numerictype( 1, nt.WordLength + 1, nt.FractionLength );
        y = fi( a, new_nt, fimath( a ) );
    else
        y = a;
    end
end


function y = fi_toint(u)
    coder.inline( 'always' );
    if isfi( u )
        nt = numerictype( u );
        s = nt.SignednessBool;
        wl = nt.WordLength;
        y = int32( fi( u, s, wl, 0, hdlfimath ) );
    else
        y = int32( u );
    end
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
