-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\USER\Desktop\Farneback_blockRAM\blockram_v2\codegen\PolyExp_pipeline1\hdlsrc\PolyExp_pipeline1_fixpt.vhd
-- Created: 2020-06-19 13:23:54
-- 
-- Generated by MATLAB 9.7, MATLAB Coder 4.3 and HDL Coder 3.15
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Design base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- data_out_0                    ce_out        1
-- data_out_1                    ce_out        1
-- data_out_2                    ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PolyExp_pipeline1_fixpt
-- Source Path: PolyExp_pipeline1_fixpt
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.PolyExp_pipeline1_fixpt_pkg.ALL;

ENTITY PolyExp_pipeline1_fixpt IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        indata_src                        :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        ce_out                            :   OUT   std_logic;
        data_out_0                        :   OUT   std_logic_vector(13 DOWNTO 0);  -- ufix14_En7
        data_out_1                        :   OUT   std_logic_vector(13 DOWNTO 0);  -- ufix14
        data_out_2                        :   OUT   std_logic_vector(13 DOWNTO 0)  -- ufix14
        );
END PolyExp_pipeline1_fixpt;


ARCHITECTURE rtl OF PolyExp_pipeline1_fixpt IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL indata_src_unsigned              : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL in_0_pipe_reg                    : vector_of_unsigned8(0 TO 1);  -- ufix8 [2]
  SIGNAL indata_src_1                     : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL data_out_0_tmp                   : unsigned(13 DOWNTO 0);  -- ufix14_En7
  SIGNAL data_out_1_tmp                   : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL data_out_2_tmp                   : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL PolyExp_pipeline1_fixpt_mul_temp : unsigned(21 DOWNTO 0);  -- ufix22_En15

BEGIN
  indata_src_unsigned <= unsigned(indata_src);

  enb <= clk_enable;

  in_0_pipe_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      in_0_pipe_reg <= (OTHERS => to_unsigned(16#00#, 8));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        in_0_pipe_reg(0) <= indata_src_unsigned;
        in_0_pipe_reg(1) <= in_0_pipe_reg(0);
      END IF;
    END IF;
  END PROCESS in_0_pipe_process;

  indata_src_1 <= in_0_pipe_reg(1);

  --HDL code generation from MATLAB function: PolyExp_pipeline1_fixpt
  --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  --                                                                          %
  --           Generated by MATLAB 9.7 and Fixed-Point Designer 6.4           %
  --                                                                          %
  --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  PolyExp_pipeline1_fixpt_mul_temp <= indata_src_1 * to_unsigned(16#2A8D#, 14);
  data_out_0_tmp <= PolyExp_pipeline1_fixpt_mul_temp(21 DOWNTO 8);
  data_out_1_tmp <= to_unsigned(16#0000#, 14);
  data_out_2_tmp <= to_unsigned(16#0000#, 14);

  data_out_0 <= std_logic_vector(data_out_0_tmp);

  data_out_1 <= std_logic_vector(data_out_1_tmp);

  data_out_2 <= std_logic_vector(data_out_2_tmp);

  ce_out <= clk_enable;

END rtl;

