%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.7 and Fixed-Point Designer 6.4           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [dx,dy] = UpdateFlow_pipeline1_wrapper_fixpt(data_in_1,data_in_2,data_in_3,data_in_4,data_in_5)
    fm = get_fimath();
    data_in_1_in = fi( data_in_1, 0, 14, 4, fm );
    data_in_2_in = fi( data_in_2, 1, 14, 6, fm );
    data_in_3_in = fi( data_in_3, 0, 14, 4, fm );
    data_in_4_in = fi( data_in_4, 1, 14, 5, fm );
    data_in_5_in = fi( data_in_5, 1, 14, 4, fm );
    [dx_out,dy_out] = UpdateFlow_pipeline1_fixpt( data_in_1_in, data_in_2_in, data_in_3_in, data_in_4_in, data_in_5_in );
    dx = double( dx_out );
    dy = double( dy_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
