-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\USER\Desktop\Farneback_blockRAM\blockram_v2\codegen\PolyExp_pipeline4\hdlsrc\PolyExp_pipeline4_fixpt_tc.vhd
-- Created: 2020-06-19 13:28:53
-- 
-- Generated by MATLAB 9.7, MATLAB Coder 4.3 and HDL Coder 3.15
-- 
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PolyExp_pipeline4_fixpt_tc
-- Source Path: PolyExp_pipeline4_fixpt_tc
-- Hierarchy Level: 1
-- 
-- Master clock enable input: clk_enable
-- 
-- enb         : identical to clk_enable
-- enb_1_18_0  : 18x slower than clk with last phase
-- enb_1_18_1  : 18x slower than clk with phase 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY PolyExp_pipeline4_fixpt_tc IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        enb                               :   OUT   std_logic;
        enb_1_18_0                        :   OUT   std_logic;
        enb_1_18_1                        :   OUT   std_logic
        );
END PolyExp_pipeline4_fixpt_tc;


ARCHITECTURE rtl OF PolyExp_pipeline4_fixpt_tc IS

  -- Signals
  SIGNAL count18                          : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL phase_all                        : std_logic;
  SIGNAL phase_0                          : std_logic;
  SIGNAL phase_0_tmp                      : std_logic;
  SIGNAL phase_1                          : std_logic;
  SIGNAL phase_1_tmp                      : std_logic;

BEGIN
  Counter18 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      count18 <= to_unsigned(1, 5);
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        IF count18 >= to_unsigned(17, 5) THEN
          count18 <= to_unsigned(0, 5);
        ELSE
          count18 <= count18 + to_unsigned(1, 5);
        END IF;
      END IF;
    END IF; 
  END PROCESS Counter18;

  phase_all <= '1' WHEN clk_enable = '1' ELSE '0';

  temp_process1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      phase_0 <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        phase_0 <= phase_0_tmp;
      END IF;
    END IF; 
  END PROCESS temp_process1;

  phase_0_tmp <= '1' WHEN count18 = to_unsigned(17, 5) AND clk_enable = '1' ELSE '0';

  temp_process2 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      phase_1 <= '1';
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        phase_1 <= phase_1_tmp;
      END IF;
    END IF; 
  END PROCESS temp_process2;

  phase_1_tmp <= '1' WHEN count18 = to_unsigned(0, 5) AND clk_enable = '1' ELSE '0';

  enb <=  phase_all AND clk_enable;

  enb_1_18_0 <=  phase_0 AND clk_enable;

  enb_1_18_1 <=  phase_1 AND clk_enable;


END rtl;

