%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.7 and Fixed-Point Designer 6.4           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function outdata = calcOpticalFlowFarneback_fixpt (indata)
%-------------------------------------------- Parameter Setting
fm = get_fimath();

width  = fi(200, 0, 8, 0, fm);
height = fi(200, 0, 8, 0, fm);
%--------------------------------------------
outdata = fi(PolyExp_pipeline1(indata), 0, 14, 7, fm);

end

function outdata = PolyExp_pipeline1(indata)
%--------------------------------------------
fm = get_fimath();

width  = fi(200, 0, 8, 0, fm);
height = fi(200, 0, 8, 0, fm);
n =fi(8, 0, 4, 0, fm);

g = fi(0.332451909263490, 0, 14, 15, fm);    
%---------------------- Initial blockram 
persistent row_RAM ctr;
if isempty(row_RAM)
	row_RAM = fi(zeros(1,fi_toint((width + n*fi(2, 0, 2, 0, fm))*fi(3, 0, 2, 0, fm)+fi(24, 0, 5, 0, fm)+ n*fi(3, 0, 2, 0, fm))), 0, 8, 0, fm);
	ctr = fi(uint8(1), 0, 8, 0, fm);
end

%---------------------- write BRAM
row_RAM(ctr*fi(3, 0, 2, 0, fm)+fi(25, 0, 5, 0, fm)) = indata;
row_RAM(ctr*fi(3, 0, 2, 0, fm)+fi(26, 0, 5, 0, fm)) = 0.0;
row_RAM(ctr*fi(3, 0, 2, 0, fm)+fi(27, 0, 5, 0, fm)) = 0.0;
%---------------------- read
data_buf = fi(row_RAM(ctr), 0, 8, 0, fm);

%---------------------- calculation
outdata = fi(data_buf*g, 0, 14, 7, fm);
%---------------------- counter
if ctr == uint8(200)
	ctr(:) = uint8(1);
else
	ctr(:) = ctr + fi(1, 0, 1, 0, fm);
end
end



function y = fi_toint(u)
    coder.inline( 'always' );
    if isfi( u )
        nt = numerictype( u );
        s = nt.SignednessBool;
        wl = nt.WordLength;
        y = int32( fi( u, s, wl, 0, hdlfimath ) );
    else
        y = int32( u );
    end
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
