%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.7 and Fixed-Point Designer 6.4           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function outdata = blockram_fixpt(indata)
fm = get_fimath();

width  = fi(200, 0, 8, 0, fm);
%---------------------- Initial blockram 
persistent row ctr;
if isempty(row)
	% p = fi([],1,24,0);
	% row = zeros(1,width,'like',p);
	row = fi(zeros(1,fi_toint(width)), 0, 23, 0, fm);
	ctr = fi(uint8(1), 0, 8, 0, fm);
end
%---------------------- write BRAM
row(ctr) = indata;
%---------------------- read
outdata = fi(row(ctr), 0, 23, 0, fm);
%---------------------- ctr counter
if ctr == uint8(200)
	ctr(:) = uint8(1);
else
	ctr(:) = ctr + fi(1, 0, 1, 0, fm);
end

end



function y = fi_toint(u)
    coder.inline( 'always' );
    if isfi( u )
        nt = numerictype( u );
        s = nt.SignednessBool;
        wl = nt.WordLength;
        y = int32( fi( u, s, wl, 0, hdlfimath ) );
    else
        y = int32( u );
    end
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
