%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.7 and Fixed-Point Designer 6.4           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [outdata_src,outdata_0_0,outdata_0_1]= PolyExp_pipeline1_fixpt(indata_src,indata_0_0,indata_0_1)
%----------------------
fm = get_fimath();

width  = fi(200, 0, 8, 0, fm);
%----------------------
persistent rRam ctr;
if isempty(rRam)
	p = fi([],1,24,0);
	rRam = zeros(1,fi_toint(width),'like',p);
	% rRam = zeros(1,width);
	ctr = fi(uint8(1), 0, 8, 0, fm);
end
%----------------------
% DataTypeMode: Fixed-point: binary point scaling
% Signedness: (1)Unsigned (0)signed
% WordLength: 8
% FractionLength: 0
bin_src = fi(indata_src,1,8,0);
bin_0_0 = fi(indata_0_0,1,8,0);
bin_0_1 = fi(indata_0_1,1,8,0);
data_in = bitconcat(bin_src,bin_0_0,bin_0_1);
BRAM_in = fi(data_in,1,24,0);
%---------------------- write BRAM
writeData = BRAM_in;
rRam(ctr) = writeData;
%---------------------- read BRAM
readData = rRam(ctr);
BRAM_out = readData;
%---------------------- operator
data_out = fi(BRAM_out,1,24,0);
y2 = bitsliceget(data_out,24,17); 
y1 = bitsliceget(data_out,16,9); 
y0 = bitsliceget(data_out,8,1); 

outdata_src = y2*fi(0.332451909263490, 0, 14, 15, fm);
outdata_0_0 = y1;
outdata_0_1 = y0;
%---------------------- ctr counter
if ctr == uint8(200)
	ctr(:) = uint8(1);
else
	ctr(:) = ctr + fi(1, 0, 1, 0, fm);
end
end



function y = fi_toint(u)
    coder.inline( 'always' );
    if isfi( u )
        nt = numerictype( u );
        s = nt.SignednessBool;
        wl = nt.WordLength;
        y = int32( fi( u, s, wl, 0, hdlfimath ) );
    else
        y = int32( u );
    end
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
