%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.7 and Fixed-Point Designer 6.4           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [outdata_src,outdata_0_0,outdata_0_1] = PolyExp_pipeline1_wrapper_fixpt(indata_src,indata_0_0,indata_0_1)
    fm = get_fimath();
    indata_src_in = fi( indata_src, 0, 8, 0, fm );
    indata_0_0_in = fi( indata_0_0, 0, 1, 0, fm );
    indata_0_1_in = fi( indata_0_1, 0, 1, 0, fm );
    [outdata_src_out,outdata_0_0_out,outdata_0_1_out] = PolyExp_pipeline1_fixpt( indata_src_in, indata_0_0_in, indata_0_1_in );
    outdata_src = outdata_src_out;
    outdata_0_0 = outdata_0_0_out;
    outdata_0_1 = outdata_0_1_out;
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
