%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.7 and Fixed-Point Designer 6.4           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [data_out_0,data_out_1,data_out_2] = PolyExp_pipeline1_wrapper_fixpt(indata_src)
    fm = get_fimath();
    indata_src_in = fi( indata_src, 0, 8, 0, fm );
    [data_out_0_out,data_out_1_out,data_out_2_out] = PolyExp_pipeline1_fixpt( indata_src_in );
    data_out_0 = double( data_out_0_out );
    data_out_1 = double( data_out_1_out );
    data_out_2 = double( data_out_2_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
